# Required
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  builder: html
  configuration: docs/conf.py

build:
  image: latest

python:
  version: 3.7
  install:
    - requirements: requirements.txt
